# Generated by Django 6.0.4 on 2026-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunkoFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('character_name', models.CharField(max_length=255, verbose_name='Персонаж')),
                ('franchise', models.CharField(max_length=255, verbose_name='Франшиза')),
                ('series', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Фигурка',
                'verbose_name_plural': 'Фигурки',
                'ordering': ['title'],
            },
        ),
    ]
