# Generated by Django 6.0.4 on 2026-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funkofigure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='figures/', verbose_name='Изображение'),
        ),
    ]
